// <auto-generated />
using System;
using AutoCareDiray.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoCareDiray.Shared.Migrations
{
    [DbContext(typeof(AppDBContex))]
    [Migration("20260516143502_Update#6")]
    partial class Update6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("AutoCareDiray.Shared.Models.Notes.VehicleNotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleNotes");
                });

            modelBuilder.Entity("AutoCareDiray.Shared.Models.RefillModel.Refill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateRefill")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GasStationName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFullTank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mileage")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Photos")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VolumeLiters")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Refills");
                });

            modelBuilder.Entity("AutoCareDiray.Shared.Models.RepairModel.Repair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommentMechanic")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentMileage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateRepair")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Job")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Photos")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpareParts")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepairTypeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("AutoCareDiray.Shared.Models.RepairModel.RepairType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalMileage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalMonth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRemoveMaintenance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsServiced")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastServiceMileage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleRepair")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransmissionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("RepairTypes");
                });

            modelBuilder.Entity("AutoCareDiray.Shared.Models.VehicleModel.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("FuelTank")
                        .HasColumnType("REAL");

                    b.Property<int>("Mileage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameVehicle")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsService")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PdfFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoVehicle")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransmissionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VinCode")
                        .HasColumnType("TEXT");

                    b.Property<double>("VolumeLiters")
                        .HasColumnType("REAL");

                    b.Property<string>("WarningRepair")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("YearPurchase")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("AutoCareDiray.Shared.Models.Notes.VehicleNotes", b =>
                {
                    b.HasOne("AutoCareDiray.Shared.Models.VehicleModel.Vehicle", null)
                        .WithMany("Notes")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoCareDiray.Shared.Models.RefillModel.Refill", b =>
                {
                    b.HasOne("AutoCareDiray.Shared.Models.VehicleModel.Vehicle", "Vehicle")
                        .WithMany("Refills")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoCareDiray.Shared.Models.RepairModel.Repair", b =>
                {
                    b.HasOne("AutoCareDiray.Shared.Models.RepairModel.RepairType", "RepairType")
                        .WithMany("Repairs")
                        .HasForeignKey("RepairTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoCareDiray.Shared.Models.VehicleModel.Vehicle", "Vehicle")
                        .WithMany("Repairs")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairType");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoCareDiray.Shared.Models.RepairModel.RepairType", b =>
                {
                    b.HasOne("AutoCareDiray.Shared.Models.VehicleModel.Vehicle", "Vehicle")
                        .WithMany("RepairTypes")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoCareDiray.Shared.Models.RepairModel.RepairType", b =>
                {
                    b.Navigation("Repairs");
                });

            modelBuilder.Entity("AutoCareDiray.Shared.Models.VehicleModel.Vehicle", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Refills");

                    b.Navigation("RepairTypes");

                    b.Navigation("Repairs");
                });
#pragma warning restore 612, 618
        }
    }
}
