// <auto-generated />
using System;
using AutoCareDiray.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoCareDiray.Shared.Migrations
{
    [DbContext(typeof(AppDBContex))]
    [Migration("20260304071738_NewMigration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("AutoCareDiray.Shared.Models.RepairModel.Repair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DateRepair")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepairTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpareParts")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepairTypeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Repairs");
                });

            modelBuilder.Entity("AutoCareDiray.Shared.Models.RepairModel.RepairType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("IntervalDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalMileagee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleRepair")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("RepairTypes");
                });

            modelBuilder.Entity("AutoCareDiray.Shared.Models.VehicleModel.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mileage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameVehicle")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("YearCreate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("YearPurchase")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("AutoCareDiray.Shared.Models.RepairModel.Repair", b =>
                {
                    b.HasOne("AutoCareDiray.Shared.Models.RepairModel.RepairType", "RepairType")
                        .WithMany("Repairs")
                        .HasForeignKey("RepairTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoCareDiray.Shared.Models.VehicleModel.Vehicle", "Vehicle")
                        .WithMany("Repairs")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairType");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoCareDiray.Shared.Models.RepairModel.RepairType", b =>
                {
                    b.HasOne("AutoCareDiray.Shared.Models.VehicleModel.Vehicle", "Vehicle")
                        .WithMany("ReepairTypes")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoCareDiray.Shared.Models.RepairModel.RepairType", b =>
                {
                    b.Navigation("Repairs");
                });

            modelBuilder.Entity("AutoCareDiray.Shared.Models.VehicleModel.Vehicle", b =>
                {
                    b.Navigation("ReepairTypes");

                    b.Navigation("Repairs");
                });
#pragma warning restore 612, 618
        }
    }
}
